## 当有改动推送到master分支时，启动Action
#name: 自动部署
#
#on:
#  push:
#    branches:
#      - master #2020年10月后github新建仓库默认分支改为main，注意更改
#
#  release:
#    types:
#      - published
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: 检查分支
#        uses: actions/checkout@v2
#        with:
#          ref: master #2020年10月后github新建仓库默认分支改为main，注意更改
#
#      - name: 安装 Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: "12.x"
#
#      - name: 安装 Hexo
#        run: |
#          export TZ='Asia/Shanghai'
#          npm install hexo-cli -g
#
#      - name: 缓存 Hexo
#        uses: actions/cache@v1
#        id: cache
#        with:
#          path: node_modules
#          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
#
#      - name: 安装依赖
#        if: steps.cache.outputs.cache-hit != 'true'
#        run: |
#          git config --global url."https://".insteadOf git://
#          npm install --save
#
#      - name: 生成静态文件
#        run: |
#          hexo clean
#          hexo g
#
##      - name: 部署到github pages
##        run: |
##          git config --global user.name "roy"
##          git config --global user.email "1842568012@qq.com"
##          git clone https://github.com/lovevivi121/lovevivi121.github.io .deploy_git
##          # 此处务必用HTTPS链接。SSH链接可能有权限报错的隐患
##          # =====注意.deploy_git前面有个空格=====
##          # 这行指令的目的是clone博客静态文件仓库，防止Hexo推送时覆盖整个静态文件仓库，而是只推送有更改的文件
##          # 我注释掉了是为了刷新整个仓库，也可以选择不注释掉，但是可能出现没有识别到的情况
##          hexo deploy
#
#      - name: 部署到云服务器
#        uses: cross-the-world/scp-pipeline@master
#        with:
#          host: ${{ secrets.USER_HOST }}
#          user: ${{ secrets.USER_NAME }}
#          pass: ${{ secrets.USER_PASS }}
#          connect_timeout: 10s
#          local: './.deploy_git/*'
#          remote: /www/wwwroot/lovevivi.cn

name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master # master 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        run: npm config set registry https://registry.npmmirror.com
        uses: theme-keep/hexo-deploy-github-pages-action@master
        env:
          PERSONAL_TOKEN: ${{ secrets.HEXO_KEEP_DEPLOY }}
          PUBLISH_REPOSITORY: lovevivi121/lovevivi121.github.io
          BRANCH: gh-pages
          PUBLISH_DIR: ./public

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: -rltgoDzvO --delete
          SOURCE: ./public/
          REMOTE_HOST: ${{ secrets.USER_HOST }}
          REMOTE_USER: ${{ secrets.USER_NAME }}
          TARGET: /www/wwwroot/lovevivi.cn/
          EXCLUDE:


